import { Injectable } from '@nestjs/common';
import { GitHubPublishResult, GitHubPublishSession } from '@smart-backlog/shared';
import { GithubMcpClientService } from '../github-mcp/github-mcp-client.service';
import { GithubProjectsService } from './github-projects.service';
import { AppLogger } from '../common/logger/app-logger.service';

export interface PublishItem {
  internalItemId: string;
  type: 'story' | 'task';
  parentInternalItemId?: string;
  title: string;
  description?: string;
  acceptanceCriteria?: string[];
  priority?: string;
  category?: string;
}

@Injectable()
export class GithubProjectsPublishService {
  private publishedIds = new Map<string, GitHubPublishResult>();

  constructor(
    private readonly mcpClient: GithubMcpClientService,
    private readonly projectsService: GithubProjectsService,
    private readonly logger: AppLogger,
  ) {}

  async publish(items: PublishItem[]): Promise<GitHubPublishSession> {
    const connection = this.projectsService.getStatus();
    const { repoOwner, repoName, owner, projectNumber } = connection;

    await this.ensureLabels(repoOwner, repoName);

    const stories = items.filter(i => i.type === 'story');
    const tasks = items.filter(i => i.type === 'task');

    const createdIssueMap = new Map<string, number>();
    const results: GitHubPublishResult[] = [];

    for (const story of stories) {
      if (this.publishedIds.has(story.internalItemId)) {
        const prev = this.publishedIds.get(story.internalItemId)!;
        results.push({ ...prev, status: 'skipped' });
        if (prev.githubIssueNumber) createdIssueMap.set(story.internalItemId, prev.githubIssueNumber);
        continue;
      }

      const result = await this.createIssue(repoOwner, repoName, story, null);
      this.publishedIds.set(story.internalItemId, result);
      results.push(result);
      if (result.githubIssueNumber) createdIssueMap.set(story.internalItemId, result.githubIssueNumber);

      if (result.status === 'created' && result.githubIssueNumber) {
        await this.addToProject(owner, projectNumber, result.githubIssueNumber, repoOwner, repoName);
      }
    }

    for (const task of tasks) {
      if (this.publishedIds.has(task.internalItemId)) {
        const prev = this.publishedIds.get(task.internalItemId)!;
        results.push({ ...prev, status: 'skipped' });
        continue;
      }

      const parentIssueNumber = task.parentInternalItemId ? createdIssueMap.get(task.parentInternalItemId) ?? null : null;
      const result = await this.createIssue(repoOwner, repoName, task, parentIssueNumber);
      this.publishedIds.set(task.internalItemId, result);
      results.push(result);

      if (result.status === 'created' && result.githubIssueNumber) {
        await this.addToProject(owner, projectNumber, result.githubIssueNumber, repoOwner, repoName);
      }
    }

    return {
      publishTimestamp: new Date(),
      projectOwner: owner,
      projectNumber,
      repoOwner,
      repoName,
      results,
    };
  }

  private buildIssueBody(item: PublishItem, parentIssueNumber: number | null): string {
    if (item.type === 'story') {
      const acs = (item.acceptanceCriteria ?? []).map(ac => `- [ ] ${ac}`).join('\n');
      return `## User Story\n\n${item.description ?? ''}\n\n## Acceptance Criteria\n\n${acs}\n\n## Metadata\n\n- **Priority**: ${item.priority ?? 'Medium'}\n- **Category**: ${item.category ?? ''}\n\n---\n*Generated by Smart Backlog Assistant*`;
    }
    const parentRef = parentIssueNumber ? `\n\nParent: #${parentIssueNumber}` : '';
    return `${item.description ?? ''}${parentRef}\n\n---\n*Generated by Smart Backlog Assistant*`;
  }

  private buildLabels(item: PublishItem): string[] {
    const labels = ['backlog-assistant'];
    if (item.priority) labels.push(`priority:${item.priority.toLowerCase()}`);
    if (item.category) labels.push(`category:${item.category.toLowerCase().replace(/\s+/g, '-')}`);
    return labels;
  }

  private async createIssue(repoOwner: string, repoName: string, item: PublishItem, parentIssueNumber: number | null): Promise<GitHubPublishResult> {
    try {
      let title = item.title;
      if (item.type === 'task' && parentIssueNumber) {
        try {
          await this.mcpClient.callTool('create_sub_issue', {
            owner: repoOwner,
            repo: repoName,
            issue_number: parentIssueNumber,
            title,
            body: this.buildIssueBody(item, parentIssueNumber),
            labels: this.buildLabels(item),
          });
        } catch (subErr: any) {
          const code = subErr?.status ?? subErr?.statusCode ?? 0;
          if (code === 404 || code === 422) {
            title = `[US#${parentIssueNumber}] ${title}`;
          } else {
            throw subErr;
          }
        }
      }

      const issueResult = await this.mcpClient.callTool('create_issue', {
        owner: repoOwner,
        repo: repoName,
        title,
        body: this.buildIssueBody(item, parentIssueNumber),
        labels: this.buildLabels(item),
      }) as any;

      const text = issueResult?.content?.[0]?.text;
      const parsed = text ? JSON.parse(text) : {};
      const issueNumber: number = parsed.number ?? 0;
      const issueUrl: string = parsed.html_url ?? `https://github.com/${repoOwner}/${repoName}/issues/${issueNumber}`;

      return {
        internalItemId: item.internalItemId,
        githubIssueNumber: issueNumber,
        githubIssueUrl: issueUrl,
        status: 'created',
        errorMessage: null,
        retryEligible: false,
      };
    } catch (err) {
      const msg = (err as Error).message ?? String(err);
      const isRateLimit = msg.includes('rate limit') || msg.includes('429');
      return {
        internalItemId: item.internalItemId,
        githubIssueNumber: null,
        githubIssueUrl: null,
        status: 'failed',
        errorMessage: isRateLimit ? `GitHub rate limit reached — retry after ${new Date(Date.now() + 3600000).toISOString()}` : msg,
        retryEligible: true,
      };
    }
  }

  private async addToProject(owner: string, projectNumber: number, issueNumber: number, repoOwner: string, repoName: string): Promise<void> {
    try {
      await this.mcpClient.callTool('add_issue_to_project', {
        owner,
        project_number: projectNumber,
        issue_number: issueNumber,
        repo_owner: repoOwner,
        repo_name: repoName,
      });
    } catch (err) {
      this.logger.warn(`Could not add issue #${issueNumber} to project: ${(err as Error).message}`, 'GithubProjectsPublishService');
    }
  }

  private async ensureLabels(repoOwner: string, repoName: string): Promise<void> {
    const labels = [
      { name: 'backlog-assistant', color: '0075ca', description: 'Generated by Smart Backlog Assistant' },
      { name: 'priority:high', color: 'd73a4a', description: 'High priority' },
      { name: 'priority:medium', color: 'e4e669', description: 'Medium priority' },
      { name: 'priority:low', color: '0e8a16', description: 'Low priority' },
    ];
    for (const label of labels) {
      try {
        await this.mcpClient.callTool('create_label', { owner: repoOwner, repo: repoName, ...label });
      } catch {
        // Label likely already exists — ignore
      }
    }
  }
}
